sudo: required
language: python
python: '3.6'
services:
  - docker
stages:
  - name: deploy
    if: tag =~ /^[0-9]+\.[0-9]+\.[0-9]+$/
before_script:
  - sed -i "s/VERSION.*/VERSION = '${TRAVIS_TAG}'/g" fandogh_cli/__init__.py
jobs:
  include:
    - stage: deploy
      script: skip
      before_deploy:
        - docker build -t fandogh-cli .
        - docker tag fandogh-cli ${DOCKER_USERNAME}/fandogh-cli
        - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
      deploy:
        - provider: script
          skip_cleanup: true
          on:
            all_branches: true
          script: docker push ${DOCKER_USERNAME}/fandogh-cli:latest
        - provider: pypi
          skip_cleanup: true
          skip_existing: true
          on:
            all_branches: true
          user: ${PYPI_USERNAME}
          password: ${PYPI_PASSWORD}
