sudo: required
language: python
python: '3.6'
services:
  - docker
branches:
  only:
  - master

script:
  - export VERSION="`python fandogh_cli/__init__.py`"
  - docker build -t fandoghpaas/fandogh-cli:$VERSION -t fandoghpaas/fandogh-cli:latest .
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin; docker push fandoghpaas/fandogh-cli:latest;  docker push fandoghpaas/fandogh-cli:$VERSION
